### ISSUE TITLE
feat: Add merge sort in cpp

### ISSUE THREAD

**Issue by RoshanMhatre** [droy312/cpp_code#13]
I would like to contribute Merge sort code in Cpp.
Please assign this issue to me and add the Hacktoberfest label to this issue.

**Comment by BharaniSri10** [comment]
i want to contribute on this .can you please assign this to me under hacktoberfest

**Comment by Supratick2001** [comment]
Hey, I am a hacktoberfest participant. I would like to contribute and fix this issue. Please assign me.

**Comment by RoshanMhatre** [comment]
@droy312 Please accept my PR #15

**Comment by Supratick2001** [comment]
@droy312 Please accept my PR #18 
I have also created a new issue as told.

**Comment by droy312** [comment]
@RoshanMhatre @Supratick2001 all the PRs are merged. Thank you for your contributions!
